<?xml version="1.0" encoding="utf-8"?><Database Name="Database" Class="DataBaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\Database.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.bingren" Member="bingren">
    <Type Name="bingren">
      <Column Name="姓名" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.bingren" Member="bingren1">
    <Type Name="bingren1">
      <Column Name="床位" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.bingren" Member="bingren2">
    <Type Name="bingren2">
      <Column Name="年龄" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.病人" Member="病人">
    <Type Name="病人">
      <Column Name="姓名" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.病人" Member="病人1">
    <Type Name="病人1">
      <Column Name="床位" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.病人" Member="病人2">
    <Type Name="病人2">
      <Column Name="年龄" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.登录" Member="登录">
    <Type Name="登录">
      <Column Name="职工编号" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.登录" Member="登录1">
    <Type Name="登录1">
      <Column Name="姓名" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.登录" Member="登录2">
    <Type Name="登录2">
      <Column Name="账号" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.登录" Member="登录3">
    <Type Name="登录3">
      <Column Name="密码" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>